version: '3'

services:

  security-demo:
    image: jwt-demo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jwt_demo
    depends_on:
      - mysql

  mysql:
    container_name: jwt_demo_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt_demo
    ports:
      - '3306:3306'

volumes:
  jwt_demo: